config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
  resources :lections do
    post 'comments', to: "comments#create"
    collection do
      get :search
    end
  end
  resources :users, only: [:update, :show, :destroy]
  get 'tagged', to: "lections#tagged"
  root to: "pages#home"
end
devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
root to: redirect("/#{I18n.default_locale}", status: 302)
get 'users/edit_multiple'
get'users/current_user_theme'
get 'ratings/create'
resources :tags
post 'comments/like_dislike'
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_liker
  update_index('lections#lection') { lections }
  has_many :comments, dependent: :destroy
  has_many :lections, dependent: :destroy
  has_many :ratings, dependent: :destroy
  validates :username,length: {maximum: 20},presence: true, uniqueness: { scope: :username, message: "must be unique for each user" },allow_nil: false

  before_create :confirmation_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable,:lockable,:omniauthable, omniauth_providers: [:facebook, :vkontakte, :twitter]

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      return registered_user if registered_user
        user = User.new(
        username:auth.extra.raw_info.name,
        provider:auth.provider,
        uid:auth.uid,
        email:auth.info.email,
        password:Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save
      user
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      flash[:notice] = 'Logged via Facebook'
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      flash[:notice] = 'Logged via Twitter'
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      flash[:notice] = 'Logged via Vkontakte'
    else
      session["devise.vkontakte_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end

end

app/controllers/users/omniauth_controller.rb
class Users::OmniauthController < ApplicationController
  def facebook
  @user = User.from_omniauth(request.env['omniauth.auth'])
  if @user.persisted?
    sign_in_and_redirect @user
    set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
  else
    flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end
end

def twitter
  @user = User.from_omniauth(request.env['omniauth.auth'])
  if @user.persisted?
    sign_in_and_redirect @user
    set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
  else
    flash[:error] = 'There was a problem signing you in through Twitter. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end
end

def vkontakte
  @user = User.from_omniauth(request.env['omniauth.auth'])
  if @user.persisted?
    sign_in_and_redirect @user
    set_flash_message(:notice, :success, kind: 'Vkontakte') if is_navigational_format?
  else
    flash[:error] = 'There was a problem signing you in through Vkontakte. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end
end

def failure
  flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
  redirect_to new_user_registration_url
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction
  respond_to :html, :json

  def show
    @user = User.find(params[:id])
    @lections= @user.lections.order(params_sort + " " + params_direction)
  end

  def current_user_theme
    current_user.update(theme: params[:theme])
    cookies[:theme]=params[:theme]
    redirect_to root_path
  end

  def destroy
    @user = User.find(params[:id])
  end

  def make_admin
    @user.each do  |user_to_admin|
      user_to_admin.admin=true
      user_to_admin.save
    end
  end

  def make_user
    @user.each do  |user_to_admin|
      user_to_admin.admin=false
      user_to_admin.save
    end
  end

  def edit_multiple
    @user=User.where(id: params[:user_ids])
    if params_edit == t('common.destroy')
      @user.destroy_all
    elsif params_edit == t('common.lock')
      @user.each {|user_to_lock| user_to_lock.lock_access! }
    elsif params_edit == t('common.unlock')
      @user.each {|user_to_unlock| user_to_unlock.unlock_access!}
    elsif params_edit == t('admin_panel.up')
      @user = make_admin
    elsif params_edit == t('admin_panel.down')
      @user = make_user
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    respond_with @user
  end

  def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
     if data = session["devise.vkonakte_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
     if data = session["devise.twitter_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
 end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def params_edit
    params[:commit]
  end

  def params_sort
    params[:sort]||"title"
  end

  def params_direction
    params[:direction]||"asc"
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"

  end

end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
end

def resource
    @resource ||= User.new
end

def resource_class
    User
end

def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
end
end

app/views/users/_change_email.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">

  <strong>  <label for="email"> <%= t('activerecord.attributes.user.email') %> </label> </strong>
  <div><%= best_in_place @user, :email, required: true, id: "email", autofocus: true %> </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
  <p> <%= t('edit.confirmation') + resource.unconfirmed_email %></p>
  <% end %>
  <strong><%= f.input :password, required: false, id: "new_password", input_html: { autocomplete: "new-password" } %>

  <%= f.input :password_confirmation,id: "confirm_password", required: false, input_html: { autocomplete: "new-password" } %>

  <%= f.input :current_password, required: true, id: "old_password", input_html: { autocomplete: "current-password" } %>
</strong>
</div>

<div class="form-actions">
  <%= f.button :submit, t('common.update'),class: "btn btn-outline-info", style: "margin: 5px"%>
</div>
<% end %>

app/views/users/_edit_widget.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h5> <%= t('common.editing') %> </h5>
        <%= link_to t('common.cancel'), registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-outline-info btn-sm", style: "float-left" %>
    </div>
    <div class="card-body">
    <strong>  <label for="username"> <%= t('activerecord.attributes.user.username') %> </label> </strong>
    <div><%= best_in_place @user, :username, :as => :input, id: "username"%></div>
    <%= render 'users/change_email' %>
    </div>
  </div>
</div>

app/views/users/_info_widget.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h5><%= t('common.info') %> </h5>
    </div>
    <div class="card-body">
        <div>
        <%= "#{t('home.user_created_at')}" + "#{@user.created_at.to_s.split('+0300')[0]}" %>
        </div>
        <%#=  @user.current_sign_in_at %>
    <%= t('home.lection') %> <strong> <%= @user.username %></strong> : <%= @user.lections.count %>
    </div>
  </div>
</div>

app/views/users/_lections_list.html.erb
<table class="table table-striped table-bordered table-list">
  <tr>
    <th><%= sortable "title", t('new.title') %></th>
    <th><%= sortable "speciality",t('new.speciality') %></th>
    <th><%= sortable "description", t('new.description') %></th>
    <th><%= sortable  "created_at", t('home.created_at') %></th>
    <th><%= t('new.tags')%></th>
    <th><%= t('home.actions')%></th>
  </tr>
  <% @lections.each do |lection| %>
  <tr>
    <td><%= truncate(lection.title, length: 10) %></td>
    <td><%= lection.speciality %></td>
    <td><%= truncate(lection.description, length: 20) %> </td>
    <td><%= lection.created_at.to_s.split('+0300')[0] %> </td>
    <td><% lection.tag_list.each do |tag| %>
      <span class="badge badge-pill badge-success"><%= tag %></span>
      <% end %>
    </td>
    <td><%= link_to t('common.show'), lection_path(lection), class: "btn btn-outline-success" %>
      <% if current_user && current_user.admin || current_user == lection.user %>
      <%= link_to t('common.edit'), edit_lection_path(lection), class: "btn btn-outline-warning" %>
      <%= link_to t('common.destroy'), lection_path(lection), method: :delete, class: "btn btn-outline-danger", style: "margin: 2px",
      data: { confirm: t('common.confirm') } %>
      <% end %></td>
    </tr>
    <% end %>
  </table>

app/views/users/edit_multiple.html.erb
<% if current_user.admin %>
<div class="container">
  <%= form_tag users_edit_multiple_path(@user), method: :get do %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default panel-table">
        <div class="panel-heading">
          <div class="row">
            <div class="col col-xs-6">
              <h3 class="panel-title" style="margin: 10px"><%=current_user.username %></h3>
            </div>

            <div class="col col-xs-6 text-right">
              <div class="btn-group mr-2" role="group" aria-label="First group">
                <%= submit_tag t('common.delete'), class: "btn btn-outline-danger" %>
                <%= submit_tag t('common.lock'), class: "btn btn-outline-warning" %>
                <%= submit_tag t('common.unlock'), class: "btn btn-outline-success" %>
              </div>
            </div>

          </div>
        </div>

        <table class="table table-striped table-bordered table-list">
          <thead>
            <tr>
              <th><%= check_box_tag('check_all', 'check_all', false, :onClick => "checkAll(this);") %></th>
              <th><%= t('activerecord.attributes.user.username') %></th>
              <th><%= t('activerecord.attributes.user.status') %></th>
              <th><%= t('activerecord.attributes.user.role') %></th>
              <th><%= t('home.user_created_at') %></th>
              <th><%= t('home.actions') %></th>
            </tr>
          </thead>

          <tbody>
            <% User.all.each do |user| %>
            <tr>
              <td align="center"><%= check_box_tag "user_ids[]", user.id %></td>
              <td><%= link_to user.username, user_path(user)  %></td>
              <td><%= user.access_locked? ? t('common.locked') : t('common.unlocked') %></td>
              <td><%= user.admin ? t('common.admin') : t('common.user') %></td>
              <td><%= user.created_at.to_s.split('+0300')[0] %></td>
              <div class="row">
              <td><%= submit_tag t('admin_panel.down'), class: "btn btn-outline-danger" %>
              <%= submit_tag t('admin_panel.up'), class: "btn btn-outline-success" %></td>
              </div>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>
<% end %>
</div>
<% else %>
<script type="text/javascript">
 window.location.href="<%= root_path %>"
</script>
<% end %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-9" style="text-align: center">
    <div class="container">
      <% if current_user && current_user.admin %>
      <%= link_to "Add as user #{@user.username}", {controller: "lections", action: "new", :admin_as_user => @user.id }, class: "btn btn-outline-info btn-sm" %>
      <% end %>
              <div id="sort_results" date-rome>
          <%= render 'users/lections_list' %>
        </div>
    </div>
  </div>
  <div class="col-md-3">
    <% if current_user == @user %>
    <%= render 'users/edit_widget'  %>
    <% end %>
    <div> <%= render 'users/info_widget' %> </div>
    </div>
</div>

app/views/users/show.js.erb
$('#sort_results').html("<%= j render 'users/lections_list' %>");