config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
  resources :lections do
    post 'comments', to: "comments#create"
    collection do
      get :search
    end
  end
  resources :users, only: [:update, :show, :destroy]
  get 'tagged', to: "lections#tagged"
  root to: "pages#home"
end
devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
root to: redirect("/#{I18n.default_locale}", status: 302)
get 'users/edit_multiple'
get'users/current_user_theme'
get 'ratings/create'
resources :tags
post 'comments/like_dislike'
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :lection, optional: true
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_lection, except: [:destroy, :like_dislike]
  before_action :authenticate_user!

  def create
    if @lection.ratings.where(user: current_user)
      @rating = edit
    else
      @rating = create_new
    end
    @rating.user = current_user
    @rating.save
    respond_to do |format|
      format.js
    end
  end

  def create_new
    @rating = @lection.ratings.new(rating: params[:rating], lection_id: params[:lection_id])
  end

  def edit
     @lection.ratings.where(user: current_user).destroy_all
    @rating = @lection.ratings.new(rating: params[:rating], lection_id: params[:lection_id])
  end

  def set_lection
    @lection = Lection.find(params[:lection_id])
  end


end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_create.html.erb
<div class="row">
  <div style= "margin: 10px"> <%= @lection.average_rating ? t('common.average_rate') +":" + @lection.average_rating.to_s : "" %></div>
  <% if current_user %>
  <% 1.upto(5) do |t| %>
  <% if @lection.current_user_rating(current_user) < t %>
  <%= link_to "☆", ratings_create_path(:lection_id => @lection.id, :rating => t ), class: "btn btn_theme", remote: true  %>
  <% else %>
  <%= link_to "⭐", ratings_create_path(:lection_id => @lection.id, :rating => t ), class: "btn btn_theme",  remote: true  %>
  <% end %>
  <% end %>
  <% end %>
</div>

app/views/ratings/create.js.erb
$('#rating_results').html("<%= j render 'ratings/create' %>");