config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
  resources :lections do
    post 'comments', to: "comments#create"
    collection do
      get :search
    end
  end
  resources :users, only: [:update, :show, :destroy]
  get 'tagged', to: "lections#tagged"
  root to: "pages#home"
end
devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
root to: redirect("/#{I18n.default_locale}", status: 302)
get 'users/edit_multiple'
get'users/current_user_theme'
get 'ratings/create'
resources :tags
post 'comments/like_dislike'
end

app/models/lection.rb
class Lection < ApplicationRecord
  update_index('lections#lection') { self }
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  acts_as_taggable_on :tags
  belongs_to :user, optional: true
  validates :title,length: {maximum: 255}, presence: true, uniqueness: { scope: :user_id, message: "must be unique for each of your posts" }
  validates :body,presence: true,length: {maximum: 45000},on: :create,allow_nil: false
  validates :speciality, length: {maximum: 20}

  def current_user_rating current_user
    if current_user_rating = self.ratings.find_by(user_id: current_user.id)
      return current_user_rating.rating.to_i
    else
      return 0
    end
  end

  def average_rating
    if self.ratings.count > 1
      rating_sum = 0
      self.ratings.pluck(:rating).each { |t| rating_sum += t }
      average_rate = rating_sum.to_f / self.ratings.count.to_f
      self.update(:average_rate => average_rate)
      return average_rate
    end
  end
end

app/controllers/lections_controller.rb
class LectionsController < ApplicationController
  before_action :set_lection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index,]
  # GET /lections
  # GET /lections.json
  def index
    @lections = Lection.all
  end

  def tag_cloud
    @tags = Lection.tag_counts_on(:tags)
  end
  def tagged
    if params[:tag].presence
      @tag = params[:tag]
      @lections = Lection.tagged_with(@tag)
    else
      @lections = Lection.all
    end
  end
  def search
    @query= params[:search_lections].presence && params[:search_lections][:query]
    if @query
      @lections=LectionsIndex.query(multi_match: {fields: ['title','description','body','user','comments'], query: @query, type: "phrase_prefix"}).objects
      if @lections.to_i > 0
        @lections
      else
        redirect_to root_path
      end
    end
  end

  def show
    @current_user = current_user
    @rating=Rating.new
    @comment = Comment.new
    @comments = @lection.comments.order( "updated_at DESC")
  end
  # GET /lections/new
  def new
    if current_user.admin and admin_as_user
      @new_user = User.find(admin_as_user)
      @lection =  @new_user.lections.new
    else
      @lection =  current_user.lections.new
    end
  end
  
  def create
    @lection = Lection.new(lection_params)
    if new_user = User.find_by(username: params[:commit].split().last)
      @lection = new_user.lections.new(lection_params)
    else
      @lection = current_user.lections.new(lection_params)
    end
    respond_to do |format|
      if @lection.save
        format.html { redirect_to @lection, notice: 'Lection was successfully created.' }
        format.json { render :show, status: :created, location: @lection }
      else
        format.html { render :new }
        format.json { render json: @lection.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /lections/1/edit
  def edit
  end

  # PATCH/PUT /lections/1
  # PATCH/PUT /lections/1.json
  def update
    respond_to do |format|
      if @lection.update(lection_params)
        format.html { redirect_to @lection, notice: 'Lection was successfully updated.' }
        format.json { render :show, status: :ok, location: @lection }
      else
        format.html { render :edit }
        format.json { render json: @lection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lections/1
  # DELETE /lections/1.json
  def destroy
    @lection.destroy
    respond_to do |format|
      format.html { redirect_to lections_url, notice: 'Lection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def admin_as_user
    params[:admin_as_user]
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_lection
    @lection = Lection.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lection_params
    params.require(:lection).permit(:title, :description, :speciality, :body, :tag_list)
  end

end

app/helpers/lections_helper.rb
module LectionsHelper
     include ActsAsTaggableOn::TagsHelper
end

app/views/lections/_form.html.erb
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $(function() {
    var dataset_string = document.getElementById('tags').dataset.autocomplete;
    var available_tags = dataset_string.slice(2, dataset_string.length - 2).split('","')

    function split(val) {
      return val.split(/ \s*/);
    }

    function extractLast(term) {
      return split(term).pop();
    }

    $("#tags")
    .autocomplete({
      minLength: 0,
      source: function( request, response ) {
        response( $.ui.autocomplete.filter(
        available_tags, extractLast(request.term)));
      },
      focus: function() {
        return false;
      },
      select: function(event, ui) {
        var terms = split(this.value);
        terms.pop();

        terms.push( ui.item.value );
        terms.push( "" );
        this.value = terms.join( " " );
        return false;
      }
    });
  });
</script>
<%= form_with(model: lection, local: true) do |form| %>
<br>
<div class="container">

  <% if lection.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(lection.errors.count, t('common.error')) %> <%= t('common.prohibited') %></h2>
    <ul>
      <% lection.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="card">

    <div class="row">
      <div class="col-md-12">
        <div class="card-header">

          <div class="row">
            <div class="col-2">
              <%= link_to t('common.back'), lections_path, :class => "btn btn-outline-info" %>
            </div>
            <h5 class="col-8" style="text-align: center"><%= t('common.new_lection')%></h5>
            <div class="col-2" style="text-align: right">
              <%= form.submit t('common.create')+" "+@new_user.username,:class => "btn btn-outline-info" %>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="card-body">
      <div class="row">
        <div class="col-md-12">

          <div class="form-group row">
            <div class= "col-4 col-form-label">
              <p>  <%= t('new.title') %></p>
            </div>
            <div class="col-8">
              <%= form.text_field :title, class: "form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <div class= "col-4 col-form-label">
              <p> <%= t('new.description') %> </p>
            </div>
            <div class="col-8">
              <%= form.text_field :description, class: "form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <div class= "col-4 col-form-label">
              <p>  <%= t('new.speciality') %> </p>
            </div>
            <div class="col-8">
              <%= form.number_field :speciality, class: "form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <div class= "col-4 col-form-label">
              <p> <%= t('new.body') %> <a href='https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'> <%= t('new.markdown') %></a></p>
            </div>
            <div class="col-8">
              <%= md_simple_editor  do %>
              <%= form.text_area :body, class: "form-control", rows: 5 %>
              <% end %>
            </div>
          </div>

          <div class="form-group row">
            <div class= "col-4 col-form-label">
              <p> <%= t('new.tags') %> </p>
            </div>
            <div class="col-8">
              <%= form.text_field :tag_list, class: "form-control ", id: "tags", data: {autocomplete: ActsAsTaggableOn::Tag.pluck(:name)} %>
            </div>
          </div>

        </div>
      </div>
    </div>

  </div>

</div>
<% end %>

app/views/lections/_lection.html.erb
<div class="card mb-4">
  <h6 class="card-header backgrond-text">
    <span data-toggle="tooltip" data-placement="left" title="Click here to see the profile">
      <%= t('home.by') %> <%=link_to lection.user.username, lection.user %></span>
      <div class="badge badge-pill badge-secondary float-right"><%= t('home.created_at')%> <%= lection.created_at.to_s.split('+0300')[0] %></div>
  </h6>
  <div class="card-body">
      <% if current_user%>
      <% if  current_user==lection.user  || current_user.admin %>
      <div class="btn-group dropright float-right">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
        <div class="dropdown-menu">
          <%= link_to   t('common.destroy'), lection,class:"dropdown-item align-middle" , method: :delete, data: { confirm: 'Are you sure?' } %>
          <td><%= link_to t('common.edit'), edit_lection_path(lection),class:"dropdown-item align-middle" %></td>
        </div>
      </div>
      <% end %>
      <% end %>
      <h1><%= lection.title %></h1>
      <hr>
      <h6 class="card-title"><%= lection.description+" | " + t('new.speciality') + lection.speciality.to_s %> </h6>
      <hr>
      <% if lection.body.length > 250 %>
      <%= truncate(lection.body, length: 250) %>
      <% else %>
      <%= markdown(lection.body) %>
      <% end %>
    </div>
    <div class="card-footer text-muted">
      <% lection.tag_list.each do |tag| %>
      <span class="badge badge-pill badge-info"><%= tag %></span>
      <% end %>
      <%= link_to t('common.read_more'), lection ,class: "btn btn-outline-info float-right"%>
    </div>
  </div>

app/views/lections/edit.html.erb
<h1>Editing Lection</h1>

<%= render 'form', lection: @lection %>

<%= link_to 'Show', @lection %> |
<%= link_to 'Back', lections_path %>

app/views/lections/index.html.erb
<div class="container">
<%= render @lections %>
</div>

app/views/lections/new.html.erb
<%= render 'form', lection: @lection %>

app/views/lections/search.html.erb
  <div class="container">
    <h3 style="margin: 20px"><%= t('home.search_for')%>  <%= @query %> </h3>
    <div class="row">
      <div class="col-md-8">
    <%= render @lections %>
    </div>
    <div class="col-md-4">
      <%= render 'layouts/widget' if current_user %>
      <%= render 'layouts/tags_widget' %>
    </div>
    </div>
    </div>

app/views/lections/show.html.erb
<div class="container">
  <div class="card mb-4">
    <h6 class="card-header">
      <%= t('home.by') %>  <%= link_to @lection.user.username, @lection.user %>
      <div class="row float-right" id="rating_results" style= "margin: 5px">
      <%= render 'ratings/create' %>
      </div>
    </h6>
    <div class="card-body">
      <span data-toggle="tooltip" data-placement="right" title="Click here to edit">
        <% if current_user %>
        <% if  current_user==@lection.user  || current_user.admin %>
        <div class="btn-group dropleft float-right">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
          <div class="dropdown-menu">
            <%= link_to t('common.destroy'), @lection,class:"dropdown-item align-middle" , method: :delete, data: { confirm: 'Are you sure?' } %>
            <td><%= link_to t('common.edit'), edit_lection_path(@lection),class:"dropdown-item align-middle" %></td>
          </div>
        </div>
        <% end %>
        <% end %>
        <h1><%= @lection.title %></h1>
        <hr>
        <h6 class="card-title"><%= "#{@lection.description}"+" | " + "#{t('new.speciality')}" + "#{@lection.speciality}" %> </h6>
        <hr>
        <%= markdown(@lection.body) %>
      </div>
      <div class="card-footer text-muted">
        <% @lection.tag_list.each do |tag| %>
        <span class="badge badge-pill badge-info"><%= tag %></span>
        <% end %>
        <div class="badge badge-pill badge-secondary float-right"><%= t('home.created_at')%><%= @lection.created_at.to_s.split('+0300')[0] %></div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h2><%= t('show.comment') %></h2>
      </div>
      <div class="card-body">
        <% if current_user %>
        <%= form_with model: [@lection,@comment] do |f| %>
        <div class="row">
          <div class="col-md-10">
          <%= f.text_field :body, class: "form-control form-control-lg" %>
          </div>
          <%= f.submit t('common.create'), class:  "btn btn-outline-info" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
  <div id="comment_pane_<%=@lection.id %>">
    <% @comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
    <% end %>
  </div>

app/views/lections/tagged.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
        <%= render @lections %>
      </div>
    <div class="col-md-4">
      <%= render 'layouts/widget' if current_user %>
      <%= render 'layouts/tags_widget' %>
    </div>
  </div>
</div>