config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
  resources :lections do
    post 'comments', to: "comments#create"
    collection do
      get :search
    end
  end
  resources :users, only: [:update, :show, :destroy]
  get 'tagged', to: "lections#tagged"
  root to: "pages#home"
end
devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
root to: redirect("/#{I18n.default_locale}", status: 302)
get 'users/edit_multiple'
get'users/current_user_theme'
get 'ratings/create'
resources :tags
post 'comments/like_dislike'
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<body>
  <div class="background-text">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Lections Sharing", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "#{current_user.username}", current_user, class: "nav-link" if current_user %>
        </li>
        <% if current_user && current_user.admin == true %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t('common.admin') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to t('common.user_panel'), users_edit_multiple_path(@user), class: "dropdown-item" %>
          </div>
        </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
        <div class="form-inline my-2 my-lg-0">
          <%= form_for :search_lections, url: search_lections_path, method: :get do |f| %>
          <%= f.text_field :query, value: params[:search_lections].presence && params[:search_lections][:query], class: "form-control mr-sm-2", placeholder: t('common.search') %>
          <%= f.submit t('common.search'), class: "btn btn-outline-success btn-sm" %>
          <% end %>
        </div>
      </ul>
      <div style="margin: 5px">
       <%= link_to "Ru", { :locale => :ru } , class: "btn btn-outline-light btn-sm" %>
       <%= link_to "En", { :locale => :en }, class: "btn btn-outline-light btn-sm" %>
       <%= link_to "Be", {:locale => :be }, class: "btn btn-outline-light btn-sm" %>
       </div>
      <% if !current_user %>
      <%= link_to t('common.sign_in'), new_user_session_path , class: "btn btn-outline-info btn-sm",style: "margin:5px"  %>
      <%= link_to t('common.sign_up') ,new_user_registration_path ,class: "btn btn-outline-primary btn-sm" %>
      <% else %>
      <%= link_to t('common.new_lection'), new_lection_path, class: "btn btn-primary btn-sm",style: "margin:5px" %>
      <%= link_to t('common.sign_out'), destroy_user_session_path,class: 'btn btn-outline-info btn-sm', method: :delete if current_user %>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/_tags_widget.html.erb
<div class="card my-2">
    <h5 class="card-header"> <%= t('home.tags')%> </h5>
  <div class="card-body">
    <div id="tagscloud">
    <% tag_cloud( Lection.tag_counts_on(:tags), %w(css1 css2 css3)) do |tag, css_class| %>
    <%= link_to tag.name, { :controller => "lections", :action => "tagged", :tag => tag.name }, class: css_class %>
  <% end %>
  </div>
  </div>
</div>

app/views/layouts/_widget.html.erb
<div class="card">
  <h5 class="card-header">
    <%= link_to current_user.username, current_user %>
    <%= link_to "Theme Mode", {controller: "users", action: "current_user_theme", theme: current_user.theme == "light" ? "dark" : "light" }, class: "btn btn-outline-info btn-sm float-right" %> 
  </h5>
  <div class="card-body">
    <div class="h6 text-muted"> <%= t('home.lection')%> </div>
    <div class="h5"><%= current_user.lections.count  %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lections</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="<%= current_user ? current_user.theme == "dark" ? "dark" : "light" : cookies[:theme] %>_theme">
      <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>